### ISSUE TITLE
Two IGC loggers created and a ton of NullPointerExceptions

### ISSUE THREAD

**Issue by Turakar** [glidernet/ogn-gateway-java#1]
Hello,
first of all: A nice project you and the other contributors built! I'm trying to get ogn-gateway-java working. Therefore I followed the guide at the wiki and deployed the jar on my server. I did not change something at the `gateway.properties` file, but I had to add an extra argument to get JMX working (`-Djava.rmi.server.hostname=xxx.xxx.xxx.xxx`). After starting with `./ogn-gateway.sh start` the log folder is populated with the data. But taking a look at `gateway.log` I can see a lot of NullPointerExceptions every few milliseconds. So here is the head of the log:

```
2018-03-29 19:03:10.863 INFO  org.ogn.gateway.OgnGateway  - starting OGN gateway process
2018-03-29 19:03:11.771 INFO  org.ogn.commons.igc.IgcLogger  - creating igc logger [log-folder: null, mode: ASYNC]
2018-03-29 19:03:12.406 INFO  org.ogn.commons.igc.IgcLogger  - creating igc logger [log-folder: log/igc, mode: ASYNC]
2018-03-29 19:03:12.424 INFO  org.ogn.commons.db.FileDbDescriptorProvider  - creating and initializing desciptor privider with parameters: uri: http://ddb.glidernet.org/download, refresh-interval: 900 class: org.ogn.commons.db.ogn.OgnDb
2018-03-29 19:03:13.026 INFO  org.ogn.gateway.OgnGateway  - simulation mode: true
2018-03-29 19:03:13.919 ERROR org.ogn.commons.igc.IgcLogger$PollerTask  - exception caught
java.lang.NullPointerException
	at java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at org.ogn.commons.utils.IgcUtils.toIgcLogFileId(IgcUtils.java:23)
	at org.ogn.commons.igc.IgcLogger.logToIgcFile(IgcLogger.java:151)
	at org.ogn.commons.igc.IgcLogger.access$100(IgcLogger.java:36)
	at org.ogn.commons.igc.IgcLogger$PollerTask.run(IgcLogger.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I wonder why there are two IgcLoggers created, one with the directory null. Is this the problem? There is a lot of data in my IGC folder anyway.

**Comment by Turakar** [comment]
Happy Easter!

**Comment by wbuczak** [comment]
Investigating and making necessary corrections...

**Comment by wbuczak** [comment]
The issue should now be fixed.  At the same time I've improved and refactored quite a few things, therefore please pull from repo and rebuild (mvn install) all 3 modules (ogn-commons-java, ogn-client-java and finally ogn-gateway-java (mvn package)

For info:  Very shortly there will be a OGN gateay docker image ready !  Than launching a gateway will be super fast and easy (just one command like:  "docker run dockerogn/ogn-gateway-java" ).  That will be literally all one needs to run a ogn-gateway container which will be subcribing to OGN, logging stuff, creating IGC files etc..

More info will follow shortly on the group & wiki

Cheers
Wojtek

**Comment by Turakar** [comment]
Problem seems to be fixed now.
